# Generated by Django 4.2 on 2023-05-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timevalue',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
