# Generated by Django 4.2 on 2023-05-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_timevalue_bus_time_bustime_times_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bustime',
            name='times',
        ),
        migrations.AddField(
            model_name='bustime',
            name='times',
            field=models.CharField(default=0.0, max_length=100),
            preserve_default=False,
        ),
    ]
